version: '3.9'
services:
  postgres:
    container_name: postgres
    image: 'postgres:16-alpine'
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=support

  support:
    build:
      context: ../
    container_name: support
    depends_on:
      - postgres
    env_file:
      - ../src/.env
      - ../src/.env.development.local
    image: 'ghcr.io/birthdayy-project/support:latest'
    ports:
      - '8282:8282'
      - '7282:7282'
    restart: always
    tty: true

volumes:
  postgres-data:
    external: true
